/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLDA_View;

import QLDA_Conecting.conect;
import QLDA_Conecting.connect;
import QLDA_DAO.CTDonHang_DAO;
import QLDA_DAO.HOADON_DAO;
import QLDA_Model.CTHoaDon;
import QLDA_Model.HOADON;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NGUYEN DUNG
 */
public class BanHang extends javax.swing.JPanel {

    DefaultTableModel tblModel;
    DefaultTableModel tblModel1;
    ArrayList<CTHoaDon> lstHoaDon;
    ArrayList<HOADON> lstHoadon1;

    /**
     * Creates new form BanHang
     */
    public BanHang() throws Exception {
        initComponents();
        jpanelhide.setVisible(false);
        initTable1();
        LoadNhanVienTable1();
        initTable();
        LoadNhanVienTable();
        showdate();
        showTime();
        HIENTHI();
        btnktsp.setEnabled(false);
        btnaddcat.setEnabled(false);
        txttinh.setEnabled(false);
        btninhoadon.setEnabled(false);
        txtmhoadon.setEnabled(false);
        txtloaisp.setEnabled(false);
    }
    Connection con;
    PreparedStatement pst;
    static int so = 0;
//    ThongKe ThongKe;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtpay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtbblance = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txttinh = new javax.swing.JButton();
        btninhoadon = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        btnaddcat = new javax.swing.JButton();
        txtmsanpham = new javax.swing.JTextField();
        txttensp = new javax.swing.JTextField();
        txtdvtinh = new javax.swing.JTextField();
        txtloaisp = new javax.swing.JComboBox<>();
        txtgiasp = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtmakh = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txttongtien = new javax.swing.JTextField();
        jpanelhide = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txttenkh = new javax.swing.JLabel();
        txtsdt = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtghichu = new javax.swing.JLabel();
        btnktsp = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtmhoadon = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecat = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/date-icon.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/Time-icon.png"))); // NOI18N

        date.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        date.setText("Ngày :");

        time.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        time.setText("Giờ :");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/User-icon.png"))); // NOI18N
        jLabel1.setText("Admin");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("HỆ THỐNG BÁN TRÀ SỮA TAKE - AWAY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(15, 15, 15)))
                .addGap(10, 10, 10))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("THANH TOÁN");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setText("Tổng Cộng : ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setText("Tiền Đưa : ");

        txttotal.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txttotal.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        txtpay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpayKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel10.setText("Tiền Thừa :");

        txtbblance.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txtbblance.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txtbblance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbblanceActionPerformed(evt);
            }
        });

        txttinh.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        txttinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/calculator-icon.png"))); // NOI18N
        txttinh.setText("Tính");
        txttinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttinhActionPerformed(evt);
            }
        });

        btninhoadon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btninhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/print-icon (1).png"))); // NOI18N
        btninhoadon.setText("In Hóa Đơn");
        btninhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninhoadonActionPerformed(evt);
            }
        });

        txtbill.setColumns(20);
        txtbill.setRows(5);
        txtbill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbillKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtbill);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txttinh)
                                .addGap(62, 62, 62))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btninhoadon)
                                .addGap(24, 24, 24))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtbblance, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(txttinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtbblance, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btninhoadon)
                .addGap(12, 12, 12))
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel7.setText("Mã Sản Phẩm :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel9.setText("Tên Sản Phẩm :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel11.setText("Loại Sản Phẩm :");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel14.setText("Đơn Vị Tính :");

        txtsoluong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtsoluongStateChanged(evt);
            }
        });
        txtsoluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsoluongKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel16.setText("Giá Sản Phẩm :");

        btnaddcat.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnaddcat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/cart-add-icon.png"))); // NOI18N
        btnaddcat.setText("Thêm Vào Giỏ Hàng");
        btnaddcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddcatActionPerformed(evt);
            }
        });

        txtmsanpham.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtmsanpham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmsanphamKeyReleased(evt);
            }
        });

        txttensp.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txttensp.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txttensp.setSelectionColor(new java.awt.Color(0, 0, 0));

        txtdvtinh.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtdvtinh.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        txtloaisp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtloaisp.setForeground(new java.awt.Color(255, 51, 51));
        txtloaisp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRÀ SỮA", "TRÀ CHANH", "KEM", "ĐỒ UỐNG" }));

        txtgiasp.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtgiasp.setDisabledTextColor(new java.awt.Color(102, 102, 102));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel17.setText("Số Lượng :");

        txtmakh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtmakh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmakhKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmakhKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 102));
        jLabel13.setText("Tổng Tiền :");

        txttongtien.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txttongtien.setForeground(new java.awt.Color(255, 102, 102));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel18.setText("Tên Khách Hàng :");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel19.setText("Ngày Vào :");

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jButton1.setText("Tìm Kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txttenkh.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        txtsdt.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel20.setText("Ghi Chú :");

        txtghichu.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N

        javax.swing.GroupLayout jpanelhideLayout = new javax.swing.GroupLayout(jpanelhide);
        jpanelhide.setLayout(jpanelhideLayout);
        jpanelhideLayout.setHorizontalGroup(
            jpanelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelhideLayout.createSequentialGroup()
                .addGroup(jpanelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelhideLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton1))
                    .addGroup(jpanelhideLayout.createSequentialGroup()
                        .addGroup(jpanelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttenkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtsdt, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(txtghichu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jpanelhideLayout.setVerticalGroup(
            jpanelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelhideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtghichu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20))
                .addContainerGap())
        );

        btnktsp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnktsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/Search-icon.png"))); // NOI18N
        btnktsp.setText("Kiểm Tra Sản Phẩm");
        btnktsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnktspActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel15.setText("Mã Khách Hàng :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel12.setText("Mã Hóa Đơn :");

        txtmhoadon.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtmhoadon.setCaretColor(new java.awt.Color(102, 102, 102));
        txtmhoadon.setDisabledTextColor(new java.awt.Color(204, 0, 51));
        txtmhoadon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmhoadonKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14))
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttensp, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(txtloaisp, 0, 135, Short.MAX_VALUE)
                            .addComponent(txtdvtinh, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(txtgiasp, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(txtsoluong)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnktsp))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtmsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel15)
                                .addGap(33, 33, 33)
                                .addComponent(txtmakh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnaddcat)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(29, 29, 29)
                                    .addComponent(txtmhoadon))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jpanelhide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 27, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtmsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtmakh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnktsp)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtloaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jpanelhide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdvtinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtmhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgiasp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addComponent(btnaddcat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        tablecat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tablecat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Mã Sản Phẩm", "Tên Sản Phẩm", "Loại Sản Phẩm", "Đơn Vị Tính", "Đơn Gía", "Số Lượng", "Thành Tiền"
            }
        ));
        tablecat.setAlignmentX(10.0F);
        tablecat.setAlignmentY(10.0F);
        tablecat.setRowHeight(28);
        jScrollPane1.setViewportView(tablecat);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(380, 380, 380)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
public void themCThoadon() throws Exception {
        StringBuilder sb = new StringBuilder();
        if (txtmhoadon.getText().equals("")) {
            sb.append("Vui lòng nhập mã hóa đơn \n");
        }
        try {
            // TODO add your handling code here:
            DefaultTableModel bulkModel = (DefaultTableModel) tablecat.getModel();
            Connection conn = connect.getConnection();
            Statement stmt = conn.createStatement();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Không thể kết nối đến máy chủ !!!");
            }
            for (int i = 0; i < bulkModel.getRowCount(); i++) {
                String MAHD = bulkModel.getValueAt(i, 0).toString();
                String MASP = bulkModel.getValueAt(i, 1).toString();
                String TENSP = bulkModel.getValueAt(i, 2).toString();
                String LOAISP = bulkModel.getValueAt(i, 3).toString();
                String DONVT = bulkModel.getValueAt(i, 4).toString();
                String DONGIA = bulkModel.getValueAt(i, 5).toString();
                String SOLUONG = bulkModel.getValueAt(i, 6).toString();
                String THANHTIEN = bulkModel.getValueAt(i, 7).toString();
                String bulkQuery = "INSERT INTO CHITIETHOADONN(MAHD,MASP,SOLUONG,DONGIA,THANHTIEN) VALUES  ('" + MAHD + "','" + MASP + "','" + SOLUONG + "','" + DONGIA + "','" + THANHTIEN + "')";
                stmt.addBatch(bulkQuery);
                LoadNhanVienTable();

            }
            int[] rowsInserted = stmt.executeBatch();
            System.out.println("Data Inserted");
            System.out.println("rowsInserted Count = " + rowsInserted.length);
            JOptionPane.showMessageDialog(null, "Thêm thành công");
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void themhoadon() {
        StringBuilder sb = new StringBuilder();
        if (txtmhoadon.getText().equals("")) {
            sb.append("Vui lòng nhập mã hóa đơn  \n");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try {
            HOADON bk = new HOADON();
            bk.setMaHoaDon(txtmhoadon.getText());
            bk.setMaKhachHang(txtmakh.getText());
            bk.setNgayLap(date.getText());
            bk.setTongTien(txttotal.getText());
            bk.setGhiChu(txtghichu.getText());
            HOADON_DAO dk = new HOADON_DAO();
            dk.insert(bk);
            LoadNhanVienTable1();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Mã Hóa Đơn này đã tồn tại trong cửa hàng.");
            e.printStackTrace();
        }
    }
    private void txtbblanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbblanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbblanceActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void btninhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninhoadonActionPerformed
//         TODO add your handling code here:
        try {
            txtbill.print();
        } catch (PrinterException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtbill.setText("");
        btninhoadon.setEnabled(false);
    }//GEN-LAST:event_btninhoadonActionPerformed

    private void txtsoluongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtsoluongStateChanged
        int qty = Integer.parseInt(txtsoluong.getValue().toString());
        int price = Integer.parseInt(txtgiasp.getText());
        int tot = qty * price;
        txttongtien.setText(String.valueOf(tot));
    }//GEN-LAST:event_txtsoluongStateChanged

    private void btnaddcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddcatActionPerformed
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) tablecat.getModel();
        model.addRow(new Object[]{
            txtmhoadon.getText(),
            txtmsanpham.getText(),
            txttensp.getText(),
            txtloaisp.getSelectedItem().toString(),
            txtdvtinh.getText(),
            txtgiasp.getText(),
            txtsoluong.getValue().toString(),
            txttongtien.getText(),});

        int sum = 0;

        for (int i = 0; i < tablecat.getRowCount(); i++) {
            sum = sum + Integer.parseInt(tablecat.getValueAt(i, 7).toString());
        }

        txttotal.setText(Integer.toString(sum));
        txttotal.setEnabled(false);
        txtmsanpham.requestFocus();
        txtmsanpham.setText("");
        txttensp.setText("");
        txtloaisp.setSelectedItem(0);
        txtdvtinh.setText("");
        txtsoluong.setValue(0);
        txttongtien.setText("");


    }//GEN-LAST:event_btnaddcatActionPerformed

    private void txttinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttinhActionPerformed

        balance();
        bill();
        themhoadon();
        try {
            themCThoadon();
        } catch (Exception ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        String id = txtmhoadon.getText();

        try {
            Connection conn = conect.getConnection();

            pst = conn.prepareStatement("insert into name(ID)values(?)");
            pst.setString(1, id);

            pst.executeUpdate();

            HIENTHI();

            txtmhoadon.setText("");
            txtmhoadon.requestFocus();

        } catch (SQLException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        }
        btninhoadon.setEnabled(true);

        txtmsanpham.setText("");
        txttensp.setText("");
        txtloaisp.setSelectedIndex(0);
        txtdvtinh.setText("");
        txtsoluong.setValue(0);
        txttongtien.setText("");
        txtmakh.setText("");
        jpanelhide.setVisible(false);
        txttotal.setText("");
        txtpay.setText("");
        txtbblance.setText("");
        btnktsp.setEnabled(false);
        btnaddcat.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) tablecat.getModel();
        model.setRowCount(0);
        txttinh.setEnabled(false);
        HIENTHI();


    }//GEN-LAST:event_txttinhActionPerformed

    private void txtmakhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmakhKeyPressed
        if (txtmakh.isVisible()) {
            jpanelhide.setVisible(true);
        } else {
            jpanelhide.setVisible(false);

        }
    }//GEN-LAST:event_txtmakhKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String pcode = txtmakh.getText();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = connect.getConnection();
            pst = con.prepareStatement("select * from KHACHHANGG where MAKH = ?");
            pst.setString(1, pcode);
            ResultSet rs = pst.executeQuery();

            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this, "Mã khách hàng này không tồn tại");
            } else {
                String tenkh = rs.getString("TENKH");
                String sdt = rs.getString("NGAYMUA");
                String thanhtoan = rs.getString("THANHTOAN");

                txttenkh.setText(tenkh.trim());
                txtsdt.setText(sdt.trim());
                txtghichu.setText(thanhtoan.trim());

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);

        }    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnktspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnktspActionPerformed
        String pcode = txtmsanpham.getText();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = connect.getConnection();
            pst = con.prepareStatement("select * from SANPHAMM where MASP = ?");
            pst.setString(1, pcode);
            ResultSet rs = pst.executeQuery();

            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this, "Mã sản phẩm này không tồn tại");
            } else {
                String Loai = rs.getString("LOAISP");
                String ten = rs.getString("TENSP");
                String dvt = rs.getString("DONVITINH");
                String gia = rs.getString("DONGIA");
                txtloaisp.setSelectedItem(Loai.trim());
                txttensp.setText(ten.trim());
                txtdvtinh.setText(dvt.trim());
                txtgiasp.setText(gia.trim());

                txtloaisp.setEnabled(false);
                txttensp.setEnabled(false);
                txtdvtinh.setEnabled(false);
                txtgiasp.setEnabled(false);

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(BanHang.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_btnktspActionPerformed

    private void txtmsanphamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmsanphamKeyReleased
        hide();        // TODO add your handling code here:
    }//GEN-LAST:event_txtmsanphamKeyReleased

    private void txtmhoadonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmhoadonKeyReleased
        hideadd();        // TODO add your handling code here:
    }//GEN-LAST:event_txtmhoadonKeyReleased

    private void txtmakhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmakhKeyReleased
        hideadd();        // TODO add your handling code here:
    }//GEN-LAST:event_txtmakhKeyReleased

    private void txtsoluongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsoluongKeyReleased
        hideadd();        // TODO add your handling code here:
    }//GEN-LAST:event_txtsoluongKeyReleased

    private void txtpayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayKeyReleased
        hide0();        // TODO add your handling code here:
    }//GEN-LAST:event_txtpayKeyReleased

    private void txtbillKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbillKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbillKeyReleased
    public void balance() {
        int total = Integer.parseInt(txttotal.getText());
        int pay = Integer.parseInt(txtpay.getText());
        int bal = pay - total;
        txtbblance.setText(String.valueOf(bal));
        txtbblance.setEnabled(false);
    }

    public void bill() {
        String total = txttotal.getText();
        String pay = txtpay.getText();
        String bal = txtbblance.getText();
        String mahd = txtmhoadon.getText();
        String tenkh = txttenkh.getText();
        String ngay = date.getText();
        String thoigian = time.getText();

        DefaultTableModel model = new DefaultTableModel();

        model = (DefaultTableModel) tablecat.getModel();

        txtbill.setText(txtbill.getText() + "                        HÓA ĐƠN THANH TOÁN                      \n");
        txtbill.setText(txtbill.getText() + "                          Tiem1998@gmail.com                          \n");
        txtbill.setText(txtbill.getText() + "                    www.facebook.tiem18998.com                   \n");
        txtbill.setText(txtbill.getText() + "----------------------------------------------------------------\n");
        txtbill.setText(txtbill.getText() + "Mã Hóa Đơn       : " + mahd);
        txtbill.setText(txtbill.getText() + "\t" + "          Ngày Bán : " + ngay + "\n");
        txtbill.setText(txtbill.getText() + "Tên Khách Hàng  : " + tenkh);
        txtbill.setText(txtbill.getText() + "\t" + "          Giờ Bán   : " + thoigian + "\n");

        txtbill.setText(txtbill.getText() + "----------------------------------------------------------------\n");
        //Heading
        txtbill.setText(txtbill.getText() + "Tên Sản Phẩm" + "\t" + "Số Lượng" + "\t" + "Đơn Gía" + "\t" + "Thành Tiền" + "\n");
        txtbill.setText(txtbill.getText() + "----------------------------------------------------------------\n");

        for (int i = 0; i < model.getRowCount(); i++) {

            String name = (String) model.getValueAt(i, 2);
            String qty = (String) model.getValueAt(i, 6);
            String price = (String) model.getValueAt(i, 5);
            String amount = (String) model.getValueAt(i, 7);
            txtbill.setText(txtbill.getText() + name + "\t" + "\t" + qty + "\t" + price + "\t" + amount + "\n");

        }

        txtbill.setText(txtbill.getText() + "\n");

        txtbill.setText(txtbill.getText() + "\t" + "\t" + "Tổng Tiền       :" + total + "\n");
        txtbill.setText(txtbill.getText() + "\t" + "\t" + "Tiền Khách Trả :" + pay + "\n");
        txtbill.setText(txtbill.getText() + "\t" + "\t" + "-------------------------" + "\n");
        txtbill.setText(txtbill.getText() + "\t" + "\t" + "Tiền Trả Khách :" + bal + "\n");
        txtbill.setText(txtbill.getText() + "\n");
        txtbill.setText(txtbill.getText() + "                      Tiệm Trà Sữa  1998                 \n");
        txtbill.setText(txtbill.getText() + "                 Địa Chỉ : 156 Trần Phú,TP.HUẾ            \n");
        txtbill.setText(txtbill.getText() + "----------------------------------------------------------------\n");
        txtbill.setText(txtbill.getText() + "\n");

        txtbill.setText(txtbill.getText() + "                     ️  Cảm ơn quý khách                   \n");

    }

    public void hide0() {
        int total = Integer.parseInt(txttotal.getText());
        int pay = Integer.parseInt(txtpay.getText());
        if ((pay > total) || (pay == total)) {
            txttinh.setEnabled(true);
        } else {
            txttinh.setEnabled(false);
        }
    }

    public void hide() {
        String masp = txtmsanpham.getText();
        if (!masp.equals("")) {
            btnktsp.setEnabled(true);
        } else {
            btnktsp.setEnabled(false);
        }
    }

    public void hideadd() {
        String masp = txtmsanpham.getText();
        String makh = txtmakh.getText();
        String mahd = txtmhoadon.getText();
        if (!masp.equals("") && !makh.equals("") && !mahd.equals("")) {
            btnaddcat.setEnabled(true);
        } else {
            btnaddcat.setEnabled(false);
        }
    }

    public void showdate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd - MM - yyyy");
        String dat = s.format(d);
        date.setText(dat);

    }

    public void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh - mm - ss");
                String tim = s.format(d);
                time.setText(tim);
            }
        }).start();
    }

    private void initTable1() {
        tblModel1 = new DefaultTableModel();
        tblModel1.setColumnIdentifiers(new String[]{"MÃ HÓA ĐƠN", "MÃ KHÁCH HÀNG", "NGÀY LẬP", "TỔNG TIỀN", "GHI CHÚ"});
//        txthoadon.setModel(tblModel);
    }

    public void LoadNhanVienTable1() throws Exception {

        lstHoadon1 = HOADON_DAO.getALL();
        if (lstHoadon1 != null) {
            tblModel1.setRowCount(0);
            for (HOADON pn : lstHoadon1) {
                Vector vec = new Vector();
                vec.add(pn.getMaHoaDon());
                vec.add(pn.getMaKhachHang());
                vec.add(pn.getNgayLap());
                vec.add(pn.getTongTien());
                vec.add(pn.getGhiChu());
                tblModel1.addRow(vec);
            }
        }
    }

    private void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"MÃ HÓA ĐƠN", "MÃ SẢN PHẨM", "SỐ LƯỢNG", "ĐƠN GIÁ", "THÀNH TIỀN"});
//        txtcthd1.setModel(tblModel);
    }

    public void LoadNhanVienTable() throws Exception {

        lstHoaDon = CTDonHang_DAO.getALL();
        if (lstHoaDon != null) {
            tblModel.setRowCount(0);
            for (CTHoaDon pn : lstHoaDon) {
                Vector vec = new Vector();
                vec.add(pn.getMaHoaDon());
                vec.add(pn.getMaSanPham());
                vec.add(pn.getSoLuong());
                vec.add(pn.getDonGia());
                vec.add(pn.getThanhTien());
                tblModel.addRow(vec);
            }
        }
    }

    public void HIENTHI() {
        try {
            Connection conn = conect.getConnection();
            Statement s = conn.createStatement();
            ResultSet rs = s.executeQuery("SELECT MAX(ID) FROM name");
            rs.next();
            rs.getString("MAX(ID)");
            if (rs.getString("MAX(ID)") == null) {
                txtmhoadon.setText("HD-0001");
            } else {
                long id = Long.parseLong(rs.getString("MAX(ID)").substring(3, rs.getString("MAX(ID)").length()));
                id++;
                txtmhoadon.setText("HD-" + String.format("%04d", id));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddcat;
    private javax.swing.JButton btninhoadon;
    private javax.swing.JButton btnktsp;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpanelhide;
    private javax.swing.JTable tablecat;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txtbblance;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtdvtinh;
    private javax.swing.JLabel txtghichu;
    private javax.swing.JTextField txtgiasp;
    private javax.swing.JComboBox<String> txtloaisp;
    private javax.swing.JTextField txtmakh;
    private javax.swing.JTextField txtmhoadon;
    private javax.swing.JTextField txtmsanpham;
    private javax.swing.JTextField txtpay;
    private javax.swing.JLabel txtsdt;
    private javax.swing.JSpinner txtsoluong;
    private javax.swing.JLabel txttenkh;
    private javax.swing.JTextField txttensp;
    private javax.swing.JButton txttinh;
    private javax.swing.JTextField txttongtien;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
