/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLDA_View;

import QLDA_Controller.Chuyenmanhinhcontroller;
import QLDA_DMbean.beant;
import java.awt.List;
import java.util.ArrayList;
import org.apache.commons.compress.utils.ChecksumCalculatingInputStream;
import QLDA_View.Changematkhau;

/**
 *
 * @author NGUYEN DUNG
 */
public class MainFrame extends javax.swing.JFrame {

    public MainFrame() throws Exception {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("QUẢN LÝ NHÂN VIÊN");
        Chuyenmanhinhcontroller controller = new Chuyenmanhinhcontroller(jorview);
        controller.Setview(JpanelTrangchu, JlabelTrangchu);
        ArrayList listItem = new ArrayList<>();
        listItem.add(new beant("TrangChu", JpanelTrangchu, JlabelTrangchu));
        listItem.add(new beant("SanPham", jpnsanpham, jlbsanpham));
        listItem.add(new beant("KhachHang", jpnkhachhang, jlbkhachhang));
        listItem.add(new beant("HoaDon", jpnhoadon, jlbhoadon));
        listItem.add(new beant("ThongKe", jpnthongke, jlbthongke));
        listItem.add(new beant("Thoat", jpnexit, jlbexit));

        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jorroot = new javax.swing.JPanel();
        jormenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JpanelTrangchu = new javax.swing.JPanel();
        JlabelTrangchu = new javax.swing.JLabel();
        jpnsanpham = new javax.swing.JPanel();
        jlbsanpham = new javax.swing.JLabel();
        jpnkhachhang = new javax.swing.JPanel();
        jlbkhachhang = new javax.swing.JLabel();
        jpnhoadon = new javax.swing.JPanel();
        jlbhoadon = new javax.swing.JLabel();
        jpnexit = new javax.swing.JPanel();
        jlbexit = new javax.swing.JLabel();
        jpnthongke = new javax.swing.JPanel();
        jlbthongke = new javax.swing.JLabel();
        jorview = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jormenu.setBackground(new java.awt.Color(82, 83, 81));
        jormenu.setToolTipText("");

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/ql_shop.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ CỬA HÀNG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        JpanelTrangchu.setBackground(new java.awt.Color(0, 204, 102));

        JlabelTrangchu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JlabelTrangchu.setForeground(new java.awt.Color(255, 255, 255));
        JlabelTrangchu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JlabelTrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/Home-icon1.png"))); // NOI18N
        JlabelTrangchu.setText("Trang Chủ");

        javax.swing.GroupLayout JpanelTrangchuLayout = new javax.swing.GroupLayout(JpanelTrangchu);
        JpanelTrangchu.setLayout(JpanelTrangchuLayout);
        JpanelTrangchuLayout.setHorizontalGroup(
            JpanelTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelTrangchuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(JlabelTrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        JpanelTrangchuLayout.setVerticalGroup(
            JpanelTrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelTrangchuLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(JlabelTrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jpnsanpham.setBackground(new java.awt.Color(0, 204, 102));

        jlbsanpham.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbsanpham.setForeground(new java.awt.Color(255, 255, 255));
        jlbsanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/tea-icon.png"))); // NOI18N
        jlbsanpham.setText("Quản Lý Sản Phẩm");

        javax.swing.GroupLayout jpnsanphamLayout = new javax.swing.GroupLayout(jpnsanpham);
        jpnsanpham.setLayout(jpnsanphamLayout);
        jpnsanphamLayout.setHorizontalGroup(
            jpnsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnsanphamLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbsanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jpnsanphamLayout.setVerticalGroup(
            jpnsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnsanphamLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnkhachhang.setBackground(new java.awt.Color(0, 204, 102));

        jlbkhachhang.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbkhachhang.setForeground(new java.awt.Color(255, 255, 255));
        jlbkhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/user.png"))); // NOI18N
        jlbkhachhang.setText("Quản Lý Khách Hàng");

        javax.swing.GroupLayout jpnkhachhangLayout = new javax.swing.GroupLayout(jpnkhachhang);
        jpnkhachhang.setLayout(jpnkhachhangLayout);
        jpnkhachhangLayout.setHorizontalGroup(
            jpnkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnkhachhangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnkhachhangLayout.setVerticalGroup(
            jpnkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnkhachhangLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnhoadon.setBackground(new java.awt.Color(0, 204, 102));

        jlbhoadon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbhoadon.setForeground(new java.awt.Color(255, 255, 255));
        jlbhoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/Order-history-icon.png"))); // NOI18N
        jlbhoadon.setText("Quản Lý Bán Hàng");

        javax.swing.GroupLayout jpnhoadonLayout = new javax.swing.GroupLayout(jpnhoadon);
        jpnhoadon.setLayout(jpnhoadonLayout);
        jpnhoadonLayout.setHorizontalGroup(
            jpnhoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnhoadonLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnhoadonLayout.setVerticalGroup(
            jpnhoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnhoadonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnexit.setBackground(new java.awt.Color(0, 204, 102));

        jlbexit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbexit.setForeground(new java.awt.Color(255, 255, 255));
        jlbexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/modify-key-icon.png"))); // NOI18N
        jlbexit.setText("Đổi Mật Khẩu");
        jlbexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbexitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnexitLayout = new javax.swing.GroupLayout(jpnexit);
        jpnexit.setLayout(jpnexitLayout);
        jpnexitLayout.setHorizontalGroup(
            jpnexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnexitLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbexit, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnexitLayout.setVerticalGroup(
            jpnexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnexitLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbexit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jpnthongke.setBackground(new java.awt.Color(0, 204, 102));

        jlbthongke.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbthongke.setForeground(new java.awt.Color(255, 255, 255));
        jlbthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLDA_ICON/payment-icon.png"))); // NOI18N
        jlbthongke.setText("Thống Kê");

        javax.swing.GroupLayout jpnthongkeLayout = new javax.swing.GroupLayout(jpnthongke);
        jpnthongke.setLayout(jpnthongkeLayout);
        jpnthongkeLayout.setHorizontalGroup(
            jpnthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnthongkeLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnthongkeLayout.setVerticalGroup(
            jpnthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnthongkeLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jlbthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jormenuLayout = new javax.swing.GroupLayout(jormenu);
        jormenu.setLayout(jormenuLayout);
        jormenuLayout.setHorizontalGroup(
            jormenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jormenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jormenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jormenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jpnthongke, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JpanelTrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnkhachhang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jpnsanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        jormenuLayout.setVerticalGroup(
            jormenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jormenuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(JpanelTrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jpnkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnhoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jpnthongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jorview.setBackground(new java.awt.Color(51, 51, 255));
        jorview.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jorviewLayout = new javax.swing.GroupLayout(jorview);
        jorview.setLayout(jorviewLayout);
        jorviewLayout.setHorizontalGroup(
            jorviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        jorviewLayout.setVerticalGroup(
            jorviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jorrootLayout = new javax.swing.GroupLayout(jorroot);
        jorroot.setLayout(jorrootLayout);
        jorrootLayout.setHorizontalGroup(
            jorrootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jorrootLayout.createSequentialGroup()
                .addComponent(jormenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jorview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jorrootLayout.setVerticalGroup(
            jorrootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jormenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jorview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jorroot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jorroot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbexitMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jlbexitMouseClicked
//public static void main(String[] args) throws Exception {
//        new  MainFrame().setVisible(true);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelTrangchu;
    private javax.swing.JPanel JpanelTrangchu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlbexit;
    private javax.swing.JLabel jlbhoadon;
    private javax.swing.JLabel jlbkhachhang;
    private javax.swing.JLabel jlbsanpham;
    private javax.swing.JLabel jlbthongke;
    private javax.swing.JPanel jormenu;
    private javax.swing.JPanel jorroot;
    private javax.swing.JPanel jorview;
    private javax.swing.JPanel jpnexit;
    private javax.swing.JPanel jpnhoadon;
    private javax.swing.JPanel jpnkhachhang;
    private javax.swing.JPanel jpnsanpham;
    private javax.swing.JPanel jpnthongke;
    // End of variables declaration//GEN-END:variables
}
